defaults: &defaults
  server: 'http://devbbb-mconf.no-ip.org/bigbluebutton/api'
  salt: '9465875d2c443fa2988e2293fb535eaf'
  version: '0.7'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults